services:
  # Pulse Broker
  pulse:
    image: marcosstefani/pulse:latest
    container_name: pulse-broker
    ports:
      - "5555:5555" # HTTP Port
      - "5556:5556" # gRPC Port
    volumes:
      - ./pulse.yml:/app/pulse.yml
    restart: always

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-broker
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    restart: always
